# Generated by Codex OpenAI.
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV ELAN_HOME=/opt/elan
ENV PATH=/root/.local/bin:/opt/elan/bin:${PATH}
ENV PYTHONPATH=/workspace/python

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    git \
    ca-certificates \
    python3 \
    python3-pip \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y

WORKDIR /workspace

COPY . /workspace

RUN lake --version
RUN lake build

CMD ["python3", "scripts/run_leandojo_examples.py"]
