# Generated by Codex OpenAI.
"""Tests for log creation and basic content checks."""

from __future__ import annotations

import json
import os
import subprocess
import sys
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
INTERACTIONS_LOG = REPO_ROOT / "logs" / "interactions.jsonl"
PROOF_STEPS_LOG = REPO_ROOT / "logs" / "proof_steps.jsonl"


class LogTests(unittest.TestCase):
    def test_logs_are_created_and_nonempty(self) -> None:
        env = os.environ.copy()
        env["PYTHONPATH"] = str(REPO_ROOT / "python")
        env["ELAN_HOME"] = str(REPO_ROOT / ".elan")
        subprocess.run(
            [sys.executable, "scripts/run_proof_logging.py"],
            cwd=REPO_ROOT,
            env=env,
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertTrue(INTERACTIONS_LOG.exists())
        self.assertTrue(PROOF_STEPS_LOG.exists())
        self.assertGreater(INTERACTIONS_LOG.stat().st_size, 0)
        self.assertGreater(PROOF_STEPS_LOG.stat().st_size, 0)

        interaction_line = INTERACTIONS_LOG.read_text(encoding="utf-8").splitlines()[0]
        proof_line = PROOF_STEPS_LOG.read_text(encoding="utf-8").splitlines()[0]
        self.assertIn("session_id", json.loads(interaction_line))
        self.assertIn("tactic_attempt", json.loads(proof_line))


if __name__ == "__main__":
    unittest.main()
