# Generated by Codex OpenAI.
"""Integration-style tests for the Lean benchmark scripts."""

from __future__ import annotations

import os
import subprocess
import sys
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


class ExampleScriptTests(unittest.TestCase):
    def test_run_examples_script(self) -> None:
        env = os.environ.copy()
        env["PYTHONPATH"] = str(REPO_ROOT / "python")
        env["ELAN_HOME"] = str(REPO_ROOT / ".elan")
        completed = subprocess.run(
            [sys.executable, "scripts/run_leandojo_examples.py"],
            cwd=REPO_ROOT,
            env=env,
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertEqual(completed.returncode, 0, msg=completed.stderr)
        self.assertIn("Recorded", completed.stdout)


if __name__ == "__main__":
    unittest.main()
