-- Generated by Codex OpenAI.
import Hypothesis.Kurepa.Lemmas

namespace Hypothesis.Kurepa

/--
Kurepa's left factorial hypothesis in modular form.
This proposition is formalized for experimentation and is intentionally unproved here.
-/
def kurepaConjectureMod : Prop :=
  ∀ n : Nat, n > 2 → leftFactorial n % n ≠ 0

/--
Kurepa's left factorial hypothesis in gcd form.
This proposition is formalized for experimentation and is intentionally unproved here.
-/
def kurepaConjectureGcd : Prop :=
  ∀ n : Nat, n > 1 → Nat.gcd (leftFactorial n) (Nat.factorial n) = 2

/-- Named modular statement for downstream tooling. -/
def kurepa_conjecture_mod :
    Prop := kurepaConjectureMod

/-- Named gcd statement for downstream tooling. -/
def kurepa_conjecture_gcd :
    Prop := kurepaConjectureGcd

end Hypothesis.Kurepa
