-- Generated by Codex OpenAI.

namespace Hypothesis.Kurepa

/-- The left factorial `!n = \sum_{i=0}^{n-1} i!`, defined recursively. -/
def leftFactorial : Nat → Nat
  | 0 => 0
  | n + 1 => leftFactorial n + Nat.factorial n

@[simp] theorem leftFactorial_zero : leftFactorial 0 = 0 := rfl

@[simp] theorem leftFactorial_succ (n : Nat) :
    leftFactorial (n + 1) = leftFactorial n + Nat.factorial n := rfl

end Hypothesis.Kurepa
