-- Generated by Codex OpenAI.
import Hypothesis.Kurepa.Conjecture

namespace Hypothesis.Kurepa

example : leftFactorial 0 = 0 := by simp
example : leftFactorial 1 = 1 := by simp
example : leftFactorial 2 = 2 := by simp
example : leftFactorial 3 = 4 := by simp
example : leftFactorial 4 = 10 := by native_decide
example : leftFactorial 5 = 34 := by native_decide

example : leftFactorial 3 % 3 ≠ 0 := by native_decide
example : leftFactorial 4 % 4 ≠ 0 := by native_decide
example : leftFactorial 5 % 5 ≠ 0 := by native_decide
example : leftFactorial 6 % 6 ≠ 0 := by native_decide
example : leftFactorial 7 % 7 ≠ 0 := by native_decide
example : leftFactorial 8 % 8 ≠ 0 := by native_decide
example : leftFactorial 9 % 9 ≠ 0 := by native_decide
example : leftFactorial 10 % 10 ≠ 0 := by native_decide

example : Nat.gcd (leftFactorial 2) (Nat.factorial 2) = 2 := by native_decide
example : Nat.gcd (leftFactorial 3) (Nat.factorial 3) = 2 := by native_decide
example : Nat.gcd (leftFactorial 4) (Nat.factorial 4) = 2 := by native_decide
example : Nat.gcd (leftFactorial 5) (Nat.factorial 5) = 2 := by native_decide
example : Nat.gcd (leftFactorial 6) (Nat.factorial 6) = 2 := by native_decide
example : Nat.gcd (leftFactorial 7) (Nat.factorial 7) = 2 := by native_decide

/-- Finite verification sample for the modular Kurepa statement. -/
theorem kurepa_mod_holds_up_to_ten :
    leftFactorial 3 % 3 ≠ 0 ∧
    leftFactorial 4 % 4 ≠ 0 ∧
    leftFactorial 5 % 5 ≠ 0 ∧
    leftFactorial 6 % 6 ≠ 0 ∧
    leftFactorial 7 % 7 ≠ 0 ∧
    leftFactorial 8 % 8 ≠ 0 ∧
    leftFactorial 9 % 9 ≠ 0 ∧
    leftFactorial 10 % 10 ≠ 0 := by
  repeat' constructor <;> native_decide

end Hypothesis.Kurepa
