-- Generated by Codex OpenAI.
-- Updated by Codex OpenAI to provide explanatory console output for a live demo.
import Hypothesis.Kurepa.Conjecture

namespace Hypothesis.Kurepa

example : leftFactorial 0 = 0 := by simp
example : leftFactorial 1 = 1 := by simp
example : leftFactorial 2 = 2 := by simp
example : leftFactorial 3 = 4 := by simp
example : leftFactorial 4 = 10 := by native_decide
example : leftFactorial 5 = 34 := by native_decide

example : leftFactorial 3 % 3 ≠ 0 := by native_decide
example : leftFactorial 4 % 4 ≠ 0 := by native_decide
example : leftFactorial 5 % 5 ≠ 0 := by native_decide
example : leftFactorial 6 % 6 ≠ 0 := by native_decide
example : leftFactorial 7 % 7 ≠ 0 := by native_decide
example : leftFactorial 8 % 8 ≠ 0 := by native_decide
example : leftFactorial 9 % 9 ≠ 0 := by native_decide
example : leftFactorial 10 % 10 ≠ 0 := by native_decide

example : Nat.gcd (leftFactorial 2) (Nat.factorial 2) = 2 := by native_decide
example : Nat.gcd (leftFactorial 3) (Nat.factorial 3) = 2 := by native_decide
example : Nat.gcd (leftFactorial 4) (Nat.factorial 4) = 2 := by native_decide
example : Nat.gcd (leftFactorial 5) (Nat.factorial 5) = 2 := by native_decide
example : Nat.gcd (leftFactorial 6) (Nat.factorial 6) = 2 := by native_decide
example : Nat.gcd (leftFactorial 7) (Nat.factorial 7) = 2 := by native_decide

/-- Finite verification sample for the modular Kurepa statement. -/
theorem kurepa_mod_holds_up_to_ten :
    leftFactorial 3 % 3 ≠ 0 ∧
    leftFactorial 4 % 4 ≠ 0 ∧
    leftFactorial 5 % 5 ≠ 0 ∧
    leftFactorial 6 % 6 ≠ 0 ∧
    leftFactorial 7 % 7 ≠ 0 ∧
    leftFactorial 8 % 8 ≠ 0 ∧
    leftFactorial 9 % 9 ≠ 0 ∧
    leftFactorial 10 % 10 ≠ 0 := by
  repeat' constructor <;> native_decide

/-
The definitions below support the printed guided demonstration.
They are intentionally simple so that the file remains readable to mathematicians.
-/

def line : String := "------------------------------------------------------------"

def boolSentence (b : Bool) : String :=
  if b then "yes" else "no"

def printLine : IO Unit :=
  IO.println line

def printTitle (title : String) : IO Unit := do
  printLine
  IO.println title
  printLine

def showLeftFactorialValue (n : Nat) : String :=
  "For n = " ++ toString n ++
  ", the left factorial !n is " ++ toString (leftFactorial n) ++ "."

def showResidueStatement (n : Nat) : String :=
  let residue := leftFactorial n % n
  "For n = " ++ toString n ++
  ", we compute !n mod n = " ++ toString residue ++
  ", so the residue is nonzero: " ++ boolSentence (residue ≠ 0) ++ "."

def showGcdStatement (n : Nat) : String :=
  let g := Nat.gcd (leftFactorial n) (Nat.factorial n)
  "For n = " ++ toString n ++
  ", gcd(!n, n!) = " ++ toString g ++ "."

def printLeftFactorialValues : IO Unit := do
  IO.println "Example 1: initial values of the left factorial."
  IO.println "We begin by recalling the definition of the left factorial."
  IO.println "By definition, !n is the sum of i! for 0 ≤ i < n."
  IO.println "These small values make the definition concrete."
  IO.println (showLeftFactorialValue 0)
  IO.println (showLeftFactorialValue 1)
  IO.println (showLeftFactorialValue 2)
  IO.println (showLeftFactorialValue 3)
  IO.println (showLeftFactorialValue 4)
  IO.println (showLeftFactorialValue 5)
  IO.println "Interpretation: the sequence begins 0, 1, 2, 4, 10, 34."
  IO.println "This is only computation, but it makes the recurrence visible."
  IO.println ""

def printResidueExamples : IO Unit := do
  IO.println "Example 2: residues modulo n."
  IO.println "Kurepa's hypothesis says that for every integer n > 2, the residue !n mod n is nonzero."
  IO.println "For a prime p, computing !p mod p is a natural first test of the conjectural pattern."
  IO.println (showResidueStatement 3)
  IO.println (showResidueStatement 5)
  IO.println (showResidueStatement 7)
  IO.println "Interpretation: in these cases the residue does not vanish."
  IO.println "These examples illustrate the statement; they do not prove it for all integers or all primes."
  IO.println ""

def printBoundedVerification : IO Unit := do
  IO.println "Example 3: bounded verification for a finite range."
  IO.println "We now check the modular condition for every n from 3 through 10."
  IO.println "Bounded verification means that one confirms a statement on a finite list of cases."
  IO.println "This is useful evidence, but it is not a proof of the universal claim."
  for n in [3, 4, 5, 6, 7, 8, 9, 10] do
    IO.println (showResidueStatement n)
  IO.println "Interpretation: each of these tested integers satisfies !n mod n ≠ 0."
  IO.println "A finite computation can guide conjecture formation and later proof search."
  IO.println ""

def printRecurrenceView : IO Unit := do
  IO.println "Example 4: the recurrence viewpoint."
  IO.println "The recurrence ! (n + 1) = !n + n! lets us pass from one value to the next by adjoining a single factorial term."
  IO.println "A recurrence state means the current value !n together with the next term n! that will be added."
  IO.println "This viewpoint is useful because it suggests invariant properties that may later be proved formally."
  IO.println ("Starting from !4 = " ++ toString (leftFactorial 4) ++ " and 4! = " ++ toString (Nat.factorial 4) ++ ",")
  IO.println ("the recurrence gives !5 = !4 + 4! = " ++ toString (leftFactorial 4) ++ " + " ++ toString (Nat.factorial 4) ++
    " = " ++ toString (leftFactorial 5) ++ ".")
  IO.println "Interpretation: the recurrence packages the sequence into a step-by-step structure."
  IO.println "That structure is often the right place to look for congruences and invariants."
  IO.println ""

def printGcdExamples : IO Unit := do
  IO.println "Example 5: the gcd formulation."
  IO.println "A commonly cited equivalent form says that for n > 1 one expects gcd(!n, n!) = 2."
  IO.println "We compute a few small cases."
  IO.println (showGcdStatement 2)
  IO.println (showGcdStatement 3)
  IO.println (showGcdStatement 4)
  IO.println (showGcdStatement 5)
  IO.println (showGcdStatement 6)
  IO.println (showGcdStatement 7)
  IO.println "Interpretation: the small cases match the expected value 2."
  IO.println "Again, these are verified computations, not a general theorem."
  IO.println ""

def printClosingSummary : IO Unit := do
  IO.println "Closing summary."
  IO.println "We have seen the definition, several exact values, residues modulo n, a finite verification range, and the recurrence step."
  IO.println "These examples are relevant because they indicate patterns that may later be organized into lemmas, invariants, or a full proof."
  IO.println "The present file is a guided computational demonstration; it does not claim a proof of Kurepa's hypothesis."

/-- Printed walkthrough for `lake env lean Hypothesis/Kurepa/Examples.lean`. -/
def runGuidedDemo : IO Unit := do
  printTitle "Kurepa's Left Factorial: A Guided Lean Demonstration"
  IO.println "Short introduction."
  IO.println "This file presents a few exact computations around the left factorial and Kurepa's hypothesis."
  IO.println "The aim is explanatory: each computation is accompanied by a brief mathematical interpretation."
  IO.println ""
  printLeftFactorialValues
  printResidueExamples
  printBoundedVerification
  printRecurrenceView
  printGcdExamples
  printClosingSummary

-- This `#eval` section is the visible lecture-style output for live demonstration.
#eval runGuidedDemo

end Hypothesis.Kurepa
