-- Generated by Codex OpenAI.
-- Updated by Codex OpenAI to provide explanatory console output for a live demo.
-- Updated by Codex OpenAI to also save the same demonstration text into logs/example_output.txt.
import Hypothesis.Kurepa.Conjecture

namespace Hypothesis.Kurepa

example : leftFactorial 0 = 0 := by simp
example : leftFactorial 1 = 1 := by simp
example : leftFactorial 2 = 2 := by simp
example : leftFactorial 3 = 4 := by simp
example : leftFactorial 4 = 10 := by native_decide
example : leftFactorial 5 = 34 := by native_decide

example : leftFactorial 3 % 3 ≠ 0 := by native_decide
example : leftFactorial 4 % 4 ≠ 0 := by native_decide
example : leftFactorial 5 % 5 ≠ 0 := by native_decide
example : leftFactorial 6 % 6 ≠ 0 := by native_decide
example : leftFactorial 7 % 7 ≠ 0 := by native_decide
example : leftFactorial 8 % 8 ≠ 0 := by native_decide
example : leftFactorial 9 % 9 ≠ 0 := by native_decide
example : leftFactorial 10 % 10 ≠ 0 := by native_decide

example : Nat.gcd (leftFactorial 2) (Nat.factorial 2) = 2 := by native_decide
example : Nat.gcd (leftFactorial 3) (Nat.factorial 3) = 2 := by native_decide
example : Nat.gcd (leftFactorial 4) (Nat.factorial 4) = 2 := by native_decide
example : Nat.gcd (leftFactorial 5) (Nat.factorial 5) = 2 := by native_decide
example : Nat.gcd (leftFactorial 6) (Nat.factorial 6) = 2 := by native_decide
example : Nat.gcd (leftFactorial 7) (Nat.factorial 7) = 2 := by native_decide

/-- Finite verification sample for the modular Kurepa statement. -/
theorem kurepa_mod_holds_up_to_ten :
    leftFactorial 3 % 3 ≠ 0 ∧
    leftFactorial 4 % 4 ≠ 0 ∧
    leftFactorial 5 % 5 ≠ 0 ∧
    leftFactorial 6 % 6 ≠ 0 ∧
    leftFactorial 7 % 7 ≠ 0 ∧
    leftFactorial 8 % 8 ≠ 0 ∧
    leftFactorial 9 % 9 ≠ 0 ∧
    leftFactorial 10 % 10 ≠ 0 := by
  repeat' constructor <;> native_decide

/-
The definitions below support the printed guided demonstration.
They are intentionally simple so that the file remains readable to mathematicians.
The same text is sent to the console and to a repository log file so that the
mathematical narrative can be reused in notes and documentation.
-/

def line : String := "------------------------------------------------------------"
def logDir : System.FilePath := "logs"
def outputFile : System.FilePath := logDir / "example_output.txt"

def boolSentence (b : Bool) : String :=
  if b then "yes" else "no"

def showLeftFactorialValue (n : Nat) : String :=
  "For n = " ++ toString n ++
  ", the left factorial !n is " ++ toString (leftFactorial n) ++ "."

def showResidueStatement (n : Nat) : String :=
  let residue := leftFactorial n % n
  "For n = " ++ toString n ++
  ", we compute !n mod n = " ++ toString residue ++
  ", so the residue is nonzero: " ++ boolSentence (residue ≠ 0) ++ "."

def showGcdStatement (n : Nat) : String :=
  let g := Nat.gcd (leftFactorial n) (Nat.factorial n)
  "For n = " ++ toString n ++
  ", gcd(!n, n!) = " ++ toString g ++ "."

def titleLines (title : String) : List String :=
  [line, title, line]

def leftFactorialValueLines : List String :=
  [ "Example 1: initial values of the left factorial."
  , "We begin by recalling the definition of the left factorial."
  , "By definition, !n is the sum of i! for 0 ≤ i < n."
  , "These small values make the definition concrete."
  , showLeftFactorialValue 0
  , showLeftFactorialValue 1
  , showLeftFactorialValue 2
  , showLeftFactorialValue 3
  , showLeftFactorialValue 4
  , showLeftFactorialValue 5
  , "Interpretation: the sequence begins 0, 1, 2, 4, 10, 34."
  , "This is only computation, but it makes the recurrence visible."
  , ""
  ]

def residueExampleLines : List String :=
  [ "Example 2: residues modulo n."
  , "Kurepa's hypothesis says that for every integer n > 2, the residue !n mod n is nonzero."
  , "For a prime p, computing !p mod p is a natural first test of the conjectural pattern."
  , showResidueStatement 3
  , showResidueStatement 5
  , showResidueStatement 7
  , "Interpretation: in these cases the residue does not vanish."
  , "These examples illustrate the statement; they do not prove it for all integers or all primes."
  , ""
  ]

def boundedVerificationLines : List String :=
  [ "Example 3: bounded verification for a finite range."
  , "We now check the modular condition for every n from 3 through 10."
  , "Bounded verification means that one confirms a statement on a finite list of cases."
  , "This is useful evidence, but it is not a proof of the universal claim."
  ] ++
  ([3, 4, 5, 6, 7, 8, 9, 10].map showResidueStatement) ++
  [ "Interpretation: each of these tested integers satisfies !n mod n ≠ 0."
  , "A finite computation can guide conjecture formation and later proof search."
  , ""
  ]

def recurrenceViewLines : List String :=
  [ "Example 4: the recurrence viewpoint."
  , "The recurrence ! (n + 1) = !n + n! lets us pass from one value to the next by adjoining a single factorial term."
  , "A recurrence state means the current value !n together with the next term n! that will be added."
  , "This viewpoint is useful because it suggests invariant properties that may later be proved formally."
  , "Starting from !4 = " ++ toString (leftFactorial 4) ++ " and 4! = " ++ toString (Nat.factorial 4) ++ ","
  , "the recurrence gives !5 = !4 + 4! = " ++ toString (leftFactorial 4) ++ " + " ++ toString (Nat.factorial 4) ++
      " = " ++ toString (leftFactorial 5) ++ "."
  , "Interpretation: the recurrence packages the sequence into a step-by-step structure."
  , "That structure is often the right place to look for congruences and invariants."
  , ""
  ]

def gcdExampleLines : List String :=
  [ "Example 5: the gcd formulation."
  , "A commonly cited equivalent form says that for n > 1 one expects gcd(!n, n!) = 2."
  , "We compute a few small cases."
  , showGcdStatement 2
  , showGcdStatement 3
  , showGcdStatement 4
  , showGcdStatement 5
  , showGcdStatement 6
  , showGcdStatement 7
  , "Interpretation: the small cases match the expected value 2."
  , "Again, these are verified computations, not a general theorem."
  , ""
  ]

def closingSummaryLines : List String :=
  [ "Closing summary."
  , "We have seen the definition, several exact values, residues modulo n, a finite verification range, and the recurrence step."
  , "These examples are relevant because they indicate patterns that may later be organized into lemmas, invariants, or a full proof."
  , "The present file is a guided computational demonstration; it does not claim a proof of Kurepa's hypothesis."
  ]

/-- This is the single source of truth for both the console lecture and the saved text file. -/
def guidedDemoLines : List String :=
  titleLines "Kurepa's Left Factorial: A Guided Lean Demonstration" ++
  [ "Short introduction."
  , "This file presents a few exact computations around the left factorial and Kurepa's hypothesis."
  , "The aim is explanatory: each computation is accompanied by a brief mathematical interpretation."
  , ""
  ] ++
  leftFactorialValueLines ++
  residueExampleLines ++
  boundedVerificationLines ++
  recurrenceViewLines ++
  gcdExampleLines ++
  closingSummaryLines

def guidedDemoText : String :=
  String.intercalate "\n" guidedDemoLines ++ "\n"

def writeGuidedDemoToFile : IO Unit := do
  IO.FS.createDirAll logDir
  IO.FS.writeFile outputFile guidedDemoText

/-- Printed walkthrough for `lake env lean Hypothesis/Kurepa/Examples.lean`. -/
def runGuidedDemo : IO Unit := do
  IO.print guidedDemoText
  writeGuidedDemoToFile

-- This `#eval` section is the visible lecture-style output for live demonstration.
#eval runGuidedDemo

end Hypothesis.Kurepa
