-- Generated by Codex OpenAI.
import Hypothesis.Kurepa.Definitions

namespace Hypothesis.Kurepa

@[simp] theorem leftFactorial_one : leftFactorial 1 = 1 := by
  simp [leftFactorial]

@[simp] theorem leftFactorial_two : leftFactorial 2 = 2 := by
  simp [leftFactorial]

@[simp] theorem leftFactorial_three : leftFactorial 3 = 4 := by
  simp [leftFactorial]

@[simp] theorem leftFactorial_four : leftFactorial 4 = 10 := by
  simp [leftFactorial]

@[simp] theorem leftFactorial_five : leftFactorial 5 = 34 := by
  simp [leftFactorial]

/-- Recursive step, restated under a reusable name. -/
theorem leftFactorial_step (n : Nat) :
    leftFactorial (n + 1) = leftFactorial n + Nat.factorial n := by
  simp [leftFactorial]

/-- Left factorial is monotone under the recursive definition. -/
theorem leftFactorial_le_succ (n : Nat) :
    leftFactorial n ≤ leftFactorial (n + 1) := by
  simpa [leftFactorial] using Nat.le_add_right (leftFactorial n) (Nat.factorial n)

end Hypothesis.Kurepa
