-- Generated by Codex OpenAI.
import Hypothesis.Kurepa.Examples

namespace Hypothesis.Kurepa

/--
Metadata describing a benchmark target. The main JSONL logging is implemented in Python,
but this structure keeps the Lean side explicit and discoverable.
-/
structure BenchmarkTarget where
  sourceFile : String
  theoremName : String
  description : String
  deriving Repr, Inhabited

def defaultTargets : List BenchmarkTarget :=
  [ { sourceFile := "Hypothesis/Kurepa/Examples.lean"
    , theoremName := "Hypothesis.Kurepa.kurepa_mod_holds_up_to_ten"
    , description := "Finite verification sample for Kurepa's modular conjecture." }
  , { sourceFile := "Hypothesis/Kurepa/Conjecture.lean"
    , theoremName := "Hypothesis.Kurepa.kurepa_conjecture_mod"
    , description := "Open modular form of Kurepa's hypothesis." }
  , { sourceFile := "Hypothesis/Kurepa/Conjecture.lean"
    , theoremName := "Hypothesis.Kurepa.kurepa_conjecture_gcd"
    , description := "Open gcd form of Kurepa's hypothesis." } ]

end Hypothesis.Kurepa
