# Generated by Codex OpenAI.
"""Run the proof logging flow for the bundled benchmark examples."""

from __future__ import annotations

from hypothesis_leandojo.examples import run_examples


def main() -> int:
    results = run_examples(session_label="proof-logging")
    print(f"Proof logging wrote {len(results)} records.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
