# Generated by Codex OpenAI.
"""Run reproducible interaction examples and emit JSONL logs."""

from __future__ import annotations

from hypothesis_leandojo.examples import run_examples


def main() -> int:
    results = run_examples()
    successes = sum(1 for item in results if item["ok"])
    print(f"Recorded {len(results)} example interactions; {successes} succeeded.")
    return 0 if successes == len(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
