# Generated by Codex OpenAI.
"""Helper for documenting or triggering LeanDojo installation."""

from __future__ import annotations

import argparse
import subprocess
import sys


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Install LeanDojo into the active Python environment."
    )
    parser.add_argument(
        "--install",
        action="store_true",
        help="Run pip install lean-dojo. Without this flag, print guidance only.",
    )
    parser.add_argument(
        "--package",
        default="lean-dojo",
        help="Python package name to install.",
    )
    args = parser.parse_args()

    if not args.install:
        print("LeanDojo setup helper")
        print("Run with --install to attempt installation via pip.")
        print("Example:")
        print(f"  {sys.executable} scripts/setup_leandojo.py --install")
        return 0

    cmd = [sys.executable, "-m", "pip", "install", args.package]
    print("Running:", " ".join(cmd))
    completed = subprocess.run(cmd, check=False)
    return completed.returncode


if __name__ == "__main__":
    raise SystemExit(main())
