# Generated by Codex OpenAI.
"""Path configuration for the benchmark tooling."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
LOG_DIR = REPO_ROOT / "logs"
INTERACTIONS_LOG = LOG_DIR / "interactions.jsonl"
PROOF_STEPS_LOG = LOG_DIR / "proof_steps.jsonl"


@dataclass(frozen=True)
class LeanTarget:
    file_path: str
    theorem_name: str
    prompt: str
