# Generated by Codex OpenAI.
"""Bundled benchmark examples for local and LeanDojo-backed interaction runs."""

from __future__ import annotations

from typing import Any

from .config import LeanTarget
from .interaction import InteractionRunner


DEFAULT_TARGETS = [
    LeanTarget(
        file_path="Hypothesis/Kurepa/Examples.lean",
        theorem_name="Hypothesis.Kurepa.kurepa_mod_holds_up_to_ten",
        prompt="Check the finite modular verification examples for n = 3..10.",
    ),
    LeanTarget(
        file_path="Hypothesis/Kurepa/Conjecture.lean",
        theorem_name="Hypothesis.Kurepa.kurepa_conjecture_mod",
        prompt="Load the open modular conjecture statement without proving it.",
    ),
]


def run_examples(session_label: str = "examples") -> list[dict[str, Any]]:
    runner = InteractionRunner(prefer_leandojo=True)
    results = []
    for target in DEFAULT_TARGETS:
        result = runner.run_target(target)
        result["session_label"] = session_label
        results.append(result)
    return results
