# Generated by Codex OpenAI.
"""Simple JSONL logger for interaction and proof-step records."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .config import INTERACTIONS_LOG, LOG_DIR, PROOF_STEPS_LOG


class JsonlLogger:
    """Append-only JSONL logger used by the benchmark scripts."""

    def __init__(self, path: Path) -> None:
        self.path = path
        LOG_DIR.mkdir(parents=True, exist_ok=True)

    def write(self, record: dict[str, Any]) -> None:
        payload = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            **record,
        }
        with self.path.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps(payload, sort_keys=True) + "\n")


interaction_logger = JsonlLogger(INTERACTIONS_LOG)
proof_logger = JsonlLogger(PROOF_STEPS_LOG)
